grails-app/domain/stalknet/Person.groovy
package stalknet

import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString
import grails.compiler.GrailsCompileStatic

@GrailsCompileStatic
@EqualsAndHashCode(includes = 'username')
@ToString(includes = 'username', includeNames = true, includePackage = false)
class Person implements Serializable {

    private static final long serialVersionUID = 1

    String realname
    String username
    String password
    int age
    String email
    static hasMany = [followed: Person, messages: Message]
    boolean enabled = true
    boolean accountExpired
    boolean accountLocked
    boolean passwordExpired

    Set<Role> getAuthorities() {
        (PersonRole.findAllByPerson(this) as List<PersonRole>)*.role as Set<Role>
    }

    static constraints = {
        username nullable: false, blank: false, unique: true, size: 3..15
        realname nullable: false, blank: false
        password nullable: false, blank: false, password: true
        email email: true, blank: false
        age min:10, max:100, blank:false
    }

    static mapping = {
        followed fetch: 'join'
        password column: '`password`'
        autowire true
        messages cascade: 'all-delete-orphan'
    }
}

grails-app/controllers/stalknet/PersonController.groovy
package stalknet

import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class PersonController {

    PersonService personService

    static allowedMethods = [save: "POST", delete: "POST"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond personService.list(params), model: [personCount: personService.count()]
    }

    def show(Long id) {
        respond personService.get(id)
    }

    def create() {
        respond new Person(params)
    }

    def save(Person person) {
        if (person == null) {
            notFound()
            return
        }

        try {
            personService.save(person)
            personService.setUserRole(person.id)
            redirect(controller: "person", action: "index")
        } catch (ValidationException e) {
            respond person.errors, view: 'create'
            return
        }
    }

    def saveSubscriber() {
        personService.saveSubscriber(params.username)
        redirect(actionName: "index")
    }

    def deleteSubscriber() {
        personService.deleteSubscriber(params.username)
        redirect(controller: "person", action: "subscribers")
    }

    def subscribers() {
        def sublist = personService.getCurrentUserSubscribtions()
        return [messages: sublist]
    }

    def adminpanel() {
        def sublist = personService.list()
        return [messages: sublist]
    }


    def edit() {
        respond personService.get(params.id)
    }

    def update(Person person) {
        if (person == null) {
            notFound()
            return
        }
        try {
            personService.update(person)
        } catch (ValidationException e) {
            respond person.errors, view: 'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'person.label', default: 'Person'), person.username])
                redirect (controller: 'person', action: 'index')
            }
            '*' { respond person, [status: OK] }
        }
    }

    def delete() {
        if (params.username == null) {
            notFound()
            return
        }
        Person pers = Person.findByUsername(params.username)
        if (params.keySet().contains("delete")) {

            personService.delete(pers.id)

            request.withFormat {
                form multipartForm {
                    flash.message = message(code: 'default.deleted.message', args: [message(code: 'person.label', default: 'Person'), pers.username])
                  redirect action: "index", method: "GET"

                }
                '*' { render status: NO_CONTENT }
            }
        }
        else {
            redirect(action: "edit", params: [id: pers.id])
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'person.label', default: 'Person'), params.id])
                redirect action: "index", method: "GET"
            }
        }
    }
}

grails-app/views/person/adminpanel.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'person.label', default: 'Person')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <div id="list-person" class="content scaffold-list" role="main">
            <h1 class="display-4"><b>Edit users</b></h1>
                <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
                </g:if>
            <table>
                <thead>
                <tr>
                    <g:sortableColumn property="realname" title="Real name"/>
                    <g:sortableColumn property="username" title="Nickname"/>
                    <sec:ifLoggedIn>
                    <td>Delete</td>
                    </sec:ifLoggedIn>
                </tr>
                </thead>
                <tbody>
                <g:render template="/templates/_fields/deleteuser" var="collection" collection="${messages}"/>
                </tbody>
            </table>
                <div class="pagination">
                <g:paginate total="${personCount ?:0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/person/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'person.label', default: 'Person')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <div id="create-person" class="content scaffold-create" role="main">
            <h1 class="display-4"><b>Register</b></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.person}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.person}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.person}" method="POST" style = "text-align: center;">
                <fieldset class="form">
                    <f:all bean="person" except="followed, enabled, accountExpired, accountLocked, passwordExpired, messages"/>
                </fieldset>
                <fieldset class="buttons">
                     <g:submitButton name="create" class="btn btn-dark" value="Register" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/person/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'person.label', default: 'Person')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-person" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-person" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.person}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.person}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.person}" method="PUT">
                <g:hiddenField name="version" value="${this.person?.version}" />
                <fieldset class="form">
                    <f:all bean="person"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/person/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'person.label', default: 'Person')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <div id="list-person" class="content scaffold-list" role="main">
            <h1 class="display-4"><b>Registered users:</b></h1>
                <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
                </g:if>
            <table>
                <thead>
                <tr>
                    <g:sortableColumn property="realname" title="Real name"/>
                    <g:sortableColumn property="username" title="Nickname"/>
                    <sec:ifLoggedIn>
                        <g:sortableColumn property="email" title="Email"/>
                        <td>Subscribe</td>
                    </sec:ifLoggedIn>
                </tr>
                </thead>
                <tbody>
                <g:render template="/templates/_fields/tableCustom" var="collection" collection="${personList}"/>
                </tbody>
            </table>
                <div class="pagination">
                <g:paginate total="${personCount ?:0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/person/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'person.label', default: 'Person')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-person" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-person" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="person" />
            <g:form resource="${this.person}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.person}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/person/subscribers.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'person.label', default: 'Person')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <div id="list-person" class="content scaffold-list" role="main">
            <h1 class="display-4"><b>Subscribtions:</b></h1>
                <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
                </g:if>
            <table>
                <thead>
                <tr>
                    <g:sortableColumn property="realname" title="Real name"/>
                    <g:sortableColumn property="username" title="Nickname"/>
                    <sec:ifLoggedIn>
                    <td>UnSubscribe</td>
                    </sec:ifLoggedIn>
                </tr>
                </thead>
                <tbody>
                <g:render template="/templates/_fields/unsubscribe" var="collection" collection="${messages}"/>
                </tbody>
            </table>
                <div class="pagination">
                <g:paginate total="${personCount ?:0}" />
            </div>
        </div>
    </body>
</html>